### ISSUE TITLE
0.2编译包有误，请重新上传编译包

### ISSUE THREAD

**Issue by waveCodeSite** [FlyingRadish/pal-server-helper#1]

**Comment by FlyingRadish** [comment]
已经更新了0.3版本，可以试一下

我这边使用的是ubuntu x64，不知道是否和你的服务器环境是否一样？

**Comment by waveCodeSite** [comment]
> 已经更新了0.3版本，可以试一下
> 
> 我这边使用的是ubuntu x64，不知道是否和你的服务器环境是否一样？

一样的，都是ubuntu x64

**Comment by waveCodeSite** [comment]
> 已经更新了0.3版本，可以试一下
> 
> 我这边使用的是ubuntu x64，不知道是否和你的服务器环境是否一样？

谢谢分享

**Comment by FlyingRadish** [comment]
@waveCodeSite  请问0.3版本正常了吗？

**Comment by waveCodeSite** [comment]
> @waveCodeSite 请问0.3版本正常了吗？

能正常用，但是服务器配置不太行，你有私服吗？

**Comment by FlyingRadish** [comment]
没有哦，我是开给几个朋友玩的，也是配置不太行，才做了这个
